[package]
name = "terminal-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
async-ssh2-tokio = "0.12.2"
crossterm = "0.29.0"
ratatui = "0.30.0"
ssh2 = "0.9.5"
tokio = { version = "1", features = ["full"] }
